import { Dispatch, ReducerAction, Reducer } from "react";

export interface ICoordinate {
  x: number;
  y: number;
  isBomb: boolean;
  isSelected: boolean;
}

export interface IGame {
  width: number;
  height: number;
  id: string;
  started: boolean;
  noBombs: number;
  noBombsFound: number;
  currentPlayer: string;
  players: string[];
  coordinates: ICoordinate[];
  tick: number;
  playerJoined: boolean;
}

export interface IGameContext {
  gameState: IGame;
  gameDispatch: Dispatch<ReducerAction<Reducer<IGame, IAction>>>;
}

export interface ISocketContext {
  socket: SocketIOClient.Socket;
  emitEvent: Function;
}

export interface IAction {
  type: string,
  payload: any,
}

export interface IPayload {
  isOK: boolean,
  data: any,
  message: string | null,
}

export interface IPlayer {
  id: string; // Identifier generated by Socket.IO
  name: string | null; // Player's name
  account: string | null; // Firebase's UID
  score: number; // Player's score
}
