export enum SocketEvent {
    CONNECTION = 'connection',
    DISCONNECT = 'disconnect',

    // Server events: [Server] -> [Client]
    TICK = 'TICK',
    NEXT_PLAYER = 'NEXT_PLAYER',
    COORDINATED_SELECTED = 'COORDINATED_SELECTED',
    WINNER = 'WINNER',
    GAME_STATE_CHANGED = 'GAME_STATE_CHANGED',
    CURRENT_PLAYER = 'CURRENT_PLAYER',

    // Client feedbacks: [Server] -> [Client]
    SELECT_COORDINATE_FEEDBACK = 'SELECT_COORDINATE_FEEDBACK',
    CREATE_GAME_FEEDBACK = 'CREATE_GAME_FEEDBACK',
    JOIN_GAME_FEEDBACK = 'JOIN_GAME_FEEDBACK',
    QUICK_MATCH_FEEDBACK = 'QUICK_MATCH_FEEDBACK',
    START_GAME_FEEDBACK = 'START_GAME_FEEDBACK',
    SET_BOARD_SIZE_FEEDBACK = 'SET_BOARD_SIZE_FEEDBACK',
    PAUSE_FEEDBACK = 'PAUSE_FEEDBACK',
    SET_NUMBER_OF_BOMB_FEEDBACK = 'SET_NUMBER_OF_BOMB_FEEDBACK',
    SET_MAX_PLAYER_FEEDBACK = 'SET_MAX_PLAYER_FEEDBACK',
    GET_CURRENT_PLAYER_FEEDBACK = 'GET_CURRENT_PLAYER_FEEDBACK',

    // Client events: [Client] -> [Server]
    SELECT_COORDINATE = 'SELECT_COORDINATE',
    CREATE_GAME = 'CREATE_GAME',
    JOIN_GAME = 'JOIN_GAME',
    QUICK_MATCH = 'QUICK_MATCH',
    START_GAME = 'START_GAME',
    SET_BOARD_SIZE = 'SET_BOARD_SIZE',
    PAUSE = 'PAUSE',
    SET_NUMBER_OF_BOMB = 'SET_NUMBER_OF_BOMB',
    SET_MAX_PLAYER = 'SET_MAX_PLAYER',
    GET_CURRENT_PLAYER = 'GET_CURRENT_PLAYER',
}
